name: Build YaPB
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake gcc-multilib g++-multilib

      - name: Configure and Build
        run: |
                git clone https://github.com/yapb/crlib ext/crlib
                
                mkdir build
                cd build
                cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS=-m32 -DCMAKE_CXX_FLAGS=-m32
                make

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: yapb-linux-so
          path: build/bin/yapb.so
